# PI4: Ciência de dados aplicada a situações de mercado

In [1]:
from src import helpers, analysis, visualizations

In [2]:
conector = helpers.ConectorBD()

## Análise exploratória

In [3]:
analysis.verificar_qualidade_dados(conector)

Idade Média dos Clientes                   44.0 anos
Idade Mediana dos Clientes                   44 anos
Receita Total Geral                  $ 25,486,128.86
Margem de Lucro Média                          40.0%
Desconto Máximo Oferecido                        20%
Quantidade de Vendas Sem Desconto            625.128
Name: Métricas Gerais de Negócio, dtype: str

In [4]:
analysis.obter_desempenho_mensal_vendas(conector)

,ano,mes,receita_total,custo_total,lucro_total,itens_vendidos,margem_lucro_pct,crescimento_receita_mom_pct
0,2023,1,1095019.20,656788.03,438230.77,128486.0,40.02,0.00
1,2023,2,968948.95,581689.52,387259.34,114154.0,39.97,-11.51
2,2023,3,1084656.09,650889.73,433765.09,127279.0,39.99,11.94
3,2023,4,1038425.32,622598.35,415827.16,122274.0,40.04,-4.26
4,2023,5,1083418.79,649925.83,433491.77,127781.0,40.01,4.33
5,2023,6,1046045.02,627889.96,418154.90,123276.0,39.97,-3.45
6,2023,7,1083223.13,650264.50,432958.32,127294.0,39.97,3.55
7,2023,8,1086689.94,651700.28,434989.24,127634.0,40.03,0.32
8,2023,9,1056935.75,634845.65,422089.21,123993.0,39.94,-2.74
9,2023,10,1071879.65,643134.31,428744.79,126607.0,40.00,1.41
10,2023,11,1039418.12,623352.19,416065.63,122440.0,40.03,-3.03
11,2023,12,1080446.31,648424.33,432020.66,126886.0,39.99,3.95
12,2024,1,1084751.00,651245.63,433505.26,127676.0,39.96,0.40
13,2024,2,1010042.22,606209.12,403832.70,119074.0,39.98,-6.89
14,2024,3,1084560.82,650492.55,434068.29,127605.0,40.02,7.38
15,2024,4,1043453.14,625910.51,417541.94,122805.0,40.02,-3.79
16,2024,5,1078643.18,647185.87,431456.80,126987.0,40.00,3.37
17,2024,6,1038214.24,622215.94,415998.20,122183.0,40.07,-3.75
18,2024,7,1085923.34,651655.05,434268.21,127768.0,39.99,4.60
19,2024,8,1082353.60,649071.15,433282.13,127646.0,40.03,-0.33
20,2024,9,1051414.03,630657.28,420756.85,123630.0,40.02,-2.86
21,2024,10,1075082.20,644835.55,430246.18,126677.0,40.02,2.25
22,2024,11,1039335.10,623716.87,415617.27,122351.0,39.99,-3.33
23,2024,12,1077249.72,646856.20,430393.92,127083.0,39.95,3.65

In [5]:
analysis.analisar_segmentacao_clientes(conector)

  faixa_etaria loyalty_member  media_gasto  soma_gasto  contagem_clientes
0        18-29            Não   510.369086  2905020.84               5692
1        18-29            Sim   508.461670  2871791.51               5648
2        30-44            Não   509.000431  3555877.01               6986
3        30-44            Sim   507.890956  3595867.97               7080
4        45-59            Não   511.444882  3604663.53               7048
5        45-59            Sim   510.045333  3617241.50               7092
6          60+            Não   512.094199  2647527.01               5170
7          60+            Sim   508.731925  2688139.49               5284

In [6]:
categoria, cacau = analysis.analisar_produtos_cacau(conector)

In [7]:
categoria

   category  cocoa_percent  volume_total  lucro_total
0      Dark             50        177723    604656.66
1      Dark             60         45028    153113.96
2      Dark             70        148133    504046.53
3      Dark             80        133125    452762.53
4      Dark             90        119238    406092.40
5      Milk             50        133849    456010.90
6      Milk             60         44359    150770.01
7      Milk             70         59593    202786.26
8      Milk             80         29821    102038.26
9      Milk             90        117997    400801.70
10  Praline             50        194147    658979.99
11  Praline             60        132568    450199.00
12  Praline             70        221229    752837.25
13  Praline             80        133315    453904.60
14  Praline             90        103176    349321.95
15  Truffle             50        119365    404554.23
16  Truffle             60        103711    353862.06
17  Truffle             70         29941    101433.03
18  Truffle             80        134296    455098.38
19  Truffle             90         74889    254254.84
20    White             50        134926    457812.56
21    White             60        118963    405105.51
22    White             70        178044    605014.39
23    White             80        118985    403884.98
24    White             90        164049    556299.93

In [8]:
cacau

      intensidade_cacau  lucro_total  volume_total
0         Amargo (>70%)   3834459.57       1128891
1  Meio Amargo (50-70%)   6261182.34       1841579

## Visualizações